#
#server:
#  port: 8085
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10000/eureka
#spring:
#  application:
#    name: consumer-demo
#  zipkin:
#    base-url: http://localhost:9411