
spring:
  application:
    name: hystrix-demo
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*