
spring:
  application:
    name: zk-provider
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
server:
  port: 9091
endpoints:
  restarts: true
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN