server:
  port: 9000
logging:
  level:
    root: WARN
    org.springframework: DEBUG
    org.springframework.cloud: DEBUG
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: study
        uri: http://www.baidu.com
        predicates:
        - Path=/index
        - Query=paramA
#      discovery:
#        locator:
#          enabled: true
eureka:
  client:
    enabled: false
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10000/eureka/
